export const FETCH_DATA1_REQUEST = "FETCH_DATA1_REQUEST";
export const FETCH_DATA1_SUCCESS = "FETCH_DATA1_SUCCESS";
export const FETCH_DATA1_ERROR = "FETCH_DATA1_ERROR";
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';